[user]
owner = chtseng
notify_line = 0
notify_email = 0
notify_sms = 0

[job]
submit_from = chtseng-ml2
submit_time = 28/04/2022 09:34:10
job_path = /data/squeue/bin/test_job.sh
run_after_submit_min = 0
esti_execute_hours = 0
want_finish_after_hours = 0

[host]
reqs_cpus = 2
reqs_ram = 4000
reqs_gram = 0

[status]
execute_host = ML2
execute_start_time = 28/04/2022 15:20:01
execute_end_time = 28/04/2022 15:21:01
execute_status = finished
execute_log = /data/squeue/jobs/logs/ML2_1651109650.log
